#%RAML 1.0 Trait
    headers:
      client_id:
        type: string
        pattern: ^[a-zA-Z0-9_.-]*$
        example: Y2xpZW50SWQ6c2VjcmV0S2V5
        description: Client ID for the respective consumer application

      client_secret:
        type: string
        pattern: ^[a-zA-Z0-9_.-]*$
        example: Y2xpZW50SWQ6c2VjcmV0S2V5
        description: Client Secret for the respective consumer application