#%RAML 1.0 DataType
  additionalProperties: false
  description: This is 201 common response type
  properties:
    recordId: 
      type: string
      description : Record Id
      required: false
    code: 
      type: string
      description : Response Code
      required: false
    message:
      type: string
      description : Response Message
      required: false 